In [1]:
(5, 7)

(5, 7)

In [2]:
5, 7

(5, 7)

In [3]:
(5,)

(5,)

In [4]:
list_a = [1,3,5,7,9]
list_b = [3,5,6,7,9]
list_a + list_b

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]

In [5]:
#np.array功能為陣列運算

import numpy as np
array_a = np.array([1,3,5,7,9])
array_b = np.array([3, 5, 6, 7, 9])
type(array_a)
array_a + array_b 

array([ 4,  8, 11, 14, 18])

In [8]:
import numpy as np

l = [[1,2,3],[2,3,4]] #二維array
array = np.array(l)
array.ndim, array.shape, array.size, array.dtype

(2, (2, 3), 6, dtype('int64'))

In [10]:
import numpy as np
np.random.randn(10, 5)

array([[-0.59348261,  0.19640323, -0.69954597,  1.22835857, -0.0976852 ],
       [ 0.42576197,  1.71638986,  0.22990803,  0.76674088,  0.64184003],
       [-0.62727422,  1.44364985, -0.34332984,  0.44375298,  1.14580385],
       [ 1.58142496,  0.71361479, -1.34030832,  0.2617841 , -0.57769873],
       [ 1.32867254, -0.9200653 , -0.02982935,  0.94873254,  0.08870331],
       [ 0.97083814,  0.04389428,  0.99050365, -0.13592737,  0.17976106],
       [ 0.83548755, -2.51710723, -0.66366634,  0.08103501,  0.39062861],
       [ 0.59358648,  2.87563289, -0.67060242,  0.05450572, -1.37863302],
       [-0.01055418,  0.0992126 , -0.98975641,  0.80153993,  0.28704943],
       [-2.9348681 , -0.26413627,  0.68527105,  0.4251348 , -0.79767386]])

In [13]:
#50個學生,每個學生有5個分數(50-100) 可重複執行
scores = np.random.randint(50,101,size=(50,5))
scores

array([[ 56,  91,  63,  83,  93],
       [ 95,  78,  81,  88,  89],
       [ 81,  82,  93,  77,  77],
       [ 67,  60,  95,  56,  88],
       [ 91,  52,  76,  57,  63],
       [ 92,  94,  87,  83,  84],
       [ 96,  84,  96,  66,  71],
       [ 68,  91,  90,  86,  72],
       [ 54,  90,  80,  84,  79],
       [ 88,  56,  53,  64,  71],
       [ 75,  82,  60,  90,  64],
       [ 65,  80,  85,  59,  57],
       [ 78,  53,  78,  65,  69],
       [ 63,  79,  88,  96,  55],
       [ 80,  88,  60,  72,  84],
       [ 93,  76,  82,  94,  95],
       [ 52,  79,  83,  80,  82],
       [ 54,  66,  96,  99,  79],
       [ 82,  66,  68,  72,  74],
       [ 58,  80,  83,  84,  85],
       [ 78,  52,  98,  81,  74],
       [ 95,  69,  54,  73,  86],
       [ 87,  93,  59,  65,  65],
       [ 57,  93, 100,  64,  76],
       [ 71,  70,  79,  84,  99],
       [ 75,  55,  94,  94,  79],
       [ 54,  86,  80,  83,  78],
       [ 90,  91,  59,  75,  97],
       [ 92,  77,  64,  79,  79],
       [ 65,  