In [2]:
values = [1, 2, 3, 4, 5]
multiply = 3

new_values = []
for i in values:
    new_values.append(i*multiply)

new_values

[3, 6, 9, 12, 15]

In [4]:
values = [1, 2, 3, 4, 5]
multiply = 3

new_values = [i*multiply for i in values]
new_values

[3, 6, 9, 12, 15]

In [5]:
values = [1, 2, 3, 4, 5]
multiply = 3
values * multiply #3倍list

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [6]:
#陣列運算(numpy/pandas)

import numpy as np
values_array = np.array([1, 2, 3, 4, 5])
type(values_array)

numpy.ndarray

In [9]:
import numpy as np
values_array = np.array([1, 2, 3, 4, 5])
multiply = 3
values_array * multiply
values_array * 0.5

array([0.5, 1. , 1.5, 2. , 2.5])

In [11]:
#多維陣列
import numpy as np
np.random.randint(50, 100, size=(5,50,5))

array([[[52, 79, 68, 85, 90],
        [84, 93, 83, 54, 50],
        [78, 65, 92, 80, 59],
        ...,
        [96, 87, 82, 94, 76],
        [88, 97, 97, 68, 81],
        [54, 89, 99, 57, 89]],

       [[51, 66, 94, 72, 60],
        [95, 52, 59, 83, 67],
        [72, 65, 81, 82, 72],
        ...,
        [99, 77, 78, 75, 57],
        [51, 93, 75, 87, 72],
        [58, 68, 64, 70, 89]],

       [[52, 95, 91, 52, 98],
        [59, 93, 98, 84, 93],
        [84, 75, 78, 82, 77],
        ...,
        [76, 77, 83, 96, 54],
        [80, 85, 72, 86, 85],
        [66, 75, 58, 93, 96]],

       [[56, 71, 84, 61, 83],
        [58, 52, 81, 62, 87],
        [91, 81, 81, 81, 84],
        ...,
        [55, 63, 68, 56, 56],
        [62, 50, 99, 52, 91],
        [97, 64, 87, 53, 92]],

       [[75, 62, 72, 66, 80],
        [93, 79, 55, 96, 75],
        [77, 55, 96, 71, 66],
        ...,
        [74, 62, 67, 60, 68],
        [58, 58, 67, 78, 69],
        [76, 65, 77, 77, 72]]])

In [12]:
import numpy as np
values_array = np.array([1, 2, 3, 4, 5])
multiply = 3
values_array * multiply
values_array ** 2 *3.14159 #圓面積

array([ 3.14159, 12.56636, 28.27431, 50.26544, 78.53975])